version: "3"
services:
  pdp-service:
    image: permitio/pdp-v2:latest
    ports:
      - "7766:7000"
    environment:
      - PDP_API_KEY=permit_key_qisRlVsY5mCgaV58OkS9oVJfWxxfu66OZ4qyIe25tr33P0xR3GlzNHFKQtUxOufLNMwPa5tTUj8eWQAzEHjqts
      - PDP_DEBUG=True
    stdin_open: true
    tty: true
